### ISSUE TITLE
mass_dns Issue

### ISSUE THREAD

**Issue by blindfuzzy** [blindfuzzy/LHF#4]
#2 @noraj1337

> # I always have this error message due to DNS resolution:
> 
> ```
> mass_dns: warning: Unable to determine any DNS servers.  #Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
> ```
> 
> even when using --system-dns option

**Comment by blindfuzzy** [comment]
@noraj1337 

Are you running this on a Virtual Machine by any chance?

**Comment by noraj** [comment]
Yes on a VM with VirtualBox 5.1

**Comment by blindfuzzy** [comment]
Can anything (but itself and the host system) be pinged from your virtual machine by IP?

**Comment by noraj** [comment]
Yes the whole internet and my LAN is pingable I configured the VM with a bridge network adapter.
I tried your tool with this ip : 8.8.8.8 (which is google DNS)

**Comment by blindfuzzy** [comment]
Can you run: 

`cat /run/resolvconf/resolv.conf`

and output the results here please.

**Comment by noraj** [comment]
```
┌─[root@parrot]─[~/CTF/IceCTF/2016]
└──╼ #cat /run/resolvconf/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search lan
```

**Comment by blindfuzzy** [comment]
Does: 

`cat /etc/resolv.conf`

return anything?

 This could be the problem of not having an established symbolic link with the `/etc/resolv.conf` from what i'm reading it has nothing to do with any tools being used inside of my script, but i'd like to get this resolved for others.

**Comment by noraj** [comment]
```
┌─[root@parrot]─[~/CTF/IceCTF/2016]
└──╼ #cat /etc/resolv.conf
┌─[root@parrot]─[~/CTF/IceCTF/2016]
└──╼ #cat /etc/resolv.conf.head 
# FrozenDNS
nameserver 92.222.97.144
nameserver 92.222.97.145

# OpenDNS
nameserver 208.67.222.222
nameserver 208.67.220.220
```

But you need to know that Parrot Security OS include a special feature : DNS requests anonymization.
But I don't know how it works maybe with a local DNS server.
I also don't know what the `/etc/resolv.conf.head` is for and if it is used by resolvconf.

**Update** : So no, there is no symbolic link.

**Comment by blindfuzzy** [comment]
Does nmap work by itself on there? Is there anyway to disable that special feature?

**Comment by noraj** [comment]
I don't know how to disable this feature, there is no easy way to do it.

nmap works by itself and in fact that's nmap that display this warning not your tool.

```
┌─[root@parrot]─[~/CTF/IceCTF/2016]
└──╼ #nmap 8.8.8.8

Starting Nmap 7.25BETA1 ( https://nmap.org ) at 2016-08-17 21:55 CEST
mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
Nmap scan report for 8.8.8.8
Host is up (0.029s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE
53/tcp open  domain

Nmap done: 1 IP address (1 host up) scanned in 5.07 seconds
```

**Comment by blindfuzzy** [comment]
Take a look at this link and see if this resolves your issue: https://ubuntuforums.org/showthread.php?t=2068299

**Comment by blindfuzzy** [comment]
This is obviously NOT an issue with LHF. I am closing this.

**Comment by noraj** [comment]
The link didn't resolv my issue but you're right, this is not a LHF issue.

**Comment by blindfuzzy** [comment]
It's probably an issue with how Parrot OS anons your DNS. I'm still looking for a solution though.

**Comment by WhiteSh4d0wzero** [comment]
did you find a solution? I have the same problem but in kali linux

**Comment by VIJAYALAKSHMIVELU** [comment]
I have also same issue in kali linux.
Any one can help me to fix this problem
