### ISSUE TITLE
arachni bug

### ISSUE THREAD

**Issue by maxnovawind75** [blindfuzzy/LHF#5]
[-] [utilities#exception_jail:428] [Errno::ENOENT] No such file or directory @ rb_sysopen - /opt/Recon/results/212.129.8.13/212.129.8.13_443_arachni.bin
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/report.rb:157:in `binwrite'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/report.rb:157:in`save'
 [-] [utilities#exception_jail:428] /usr/share/arachni/ui/cli/framework.rb:378:in `generate_reports'
 [-] [utilities#exception_jail:428] /usr/share/arachni/ui/cli/framework.rb:363:in`block (2 levels) in shutdown'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /usr/share/arachni/ui/cli/framework.rb:354:in`block in shutdown'
 [-] [utilities#exception_jail:429] 
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::UI::CLI::Framework
 [-] [utilities#exception_jail:432] 
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #Proc:0x007fc2506fcc90@/usr/share/arachni/ui/cli/framework.rb:354
 [-] [utilities#exception_jail:435] 
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'

When arachni tool use in your script there are bug always the same bug.

**Comment by blindfuzzy** [comment]
Are you running this in Kali 2.0? Was this the output as the tool ran or the output of a file in the results folder?

**Comment by blindfuzzy** [comment]
I have fixed this issue. Just make sure LHF is in /opt and you will have zero issues with Arachni.
