### ISSUE TITLE
Issue on Windows (8.1)

### ISSUE THREAD

**Issue by touseefgul** [blindfuzzy/LHF#6]
Hi,
Hope that you are doing good, I just start using this tool, on windows, its saying, nmap not recognized, stty not recognize, you can see the picture below.
![seethis](https://cloud.githubusercontent.com/assets/21283111/18029900/466eb724-6cb6-11e6-92b9-9e04682bc1d3.jpg)

**Comment by blindfuzzy** [comment]
This tool has not been tested on Windows. I can add it to the Operating System test list though. However, it does work on the latest Kali Linux Distro. 

I am hoping to have time in the next few weeks to begin testing this on various operating systems. 

Note: This tool was never intended to run on Windows as some of the Modules used in the tool might not be compatible with Windows.
